Integrated Katacoda tutorials in explore section
devonfw/devonfw.github.io pull request #122
Opened 2020-10-12 08:35 UTC by GuentherJulian

2020-10-12 12:01 UTC, maybeec requested changes

2020-10-12 12:01 UTC, maybeec commented on website/pages/explore/dir-content/cobigen-tutorial.asciidoc
> += COBIGEN TUTORIAL
I think we should not introduce additional nodes but simply add the links to the already available nodes like cobigen.
Same for the other nodes

2020-10-12 15:48 UTC, GuentherJulian commented on website/pages/explore/dir-content/cobigen-tutorial.asciidoc
> += COBIGEN TUTORIAL
I've integrated the kafka and cobigen tutorials. What do you think is the best place for the jump-the-queue and my-thai-star links?

2020-10-12 18:04 UTC, maybeec commented on website/pages/explore/dir-content/cobigen-tutorial.asciidoc
> += COBIGEN TUTORIAL
Both are samples, maybe we should add a new samples folder and add mythaistar and jump the queue in Teo different nodes where we could also link to the github repo and docs sections.

2020-10-13 07:51 UTC, GuentherJulian commented on website/pages/explore/dir-content/cobigen-tutorial.asciidoc
> += COBIGEN TUTORIAL
I have created now a new samples node with two separate nodes for both of them.

2020-10-16 08:39 UTC, merged