added devonfw/journey to build-and-deploy.yml
devonfw/devonfw.github.io pull request #324
Opened 2022-06-13 12:47 UTC by vlad961

updated build-and-deploy.yml with devonfw/journeys scripts, npm install and ng build.

2022-06-13 12:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/devonfw.github.io?pullRequest=324) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/devonfw.github.io?pullRequest=324) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/devonfw.github.io?pullRequest=324) it.</sub>

2022-06-14 05:05 UTC, SchettlerKoehler requested changes

2022-06-14 05:05 UTC, SchettlerKoehler commented on .github/workflows/build-and-deploy.yml
> +      - name: install for Journeys/app
"npm install for Journeys/app"

2022-06-14 05:05 UTC, SchettlerKoehler commented on .github/workflows/build-and-deploy.yml
> +          npm install
I think this could be to late here as you are already calling the script in line 65

2022-06-14 05:05 UTC, SchettlerKoehler commented on .github/workflows/build-and-deploy.yml
> +          journeys/scripts/createOutput.sh
Please align with the rest of the team on the output path. Currently it looks strange

2022-06-14 05:05 UTC, SchettlerKoehler commented on .github/workflows/build-and-deploy.yml
> +          mv target/generated-docs/website/pages/journeys/journeys target/generated-docs/website/pages/journeys/journey
Why is that needed? It looks like createOutput is doing something in that direction already.

2022-06-14 07:30 UTC, vlad961 commented on .github/workflows/build-and-deploy.yml
> +          npm install
I changed the order of the commands and put the npm install before the run command for the script. 
~~In case all jobs are done parallel (default behaviour if I understand the documentation correctly https://docs.github.com/en/actions/using-workflows/about-workflows#creating-dependent-jobs) shall I modify the run of the script like following:~~

~~name: Copy pom files for journeys~~
~~needs: npm install for Journeys/scripts~~
~~run: | node journeys/scripts/copyPomFiles.js~~

2022-06-21 07:50 UTC, vlad961 reviewed
commit approved

2022-06-21 07:55 UTC, SchettlerKoehler approved these changes

2022-06-21 07:55 UTC, merged